# hyprpaper — wallpaper (the actual application is done by scripts/wallpaper.sh via IPC)
preload = /home/diegoveme/.config/hypr/current-wallpaper
wallpaper = eDP-1,/home/diegoveme/.config/hypr/current-wallpaper
splash = false
ipc = on
